name: Client pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Client_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v4
      - name: Start node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Lint project
        run: npm run lint
      - name: Build project
        run: npm run build
      - name: Check unit test
        run: npm run test:unit
      - name: Check screenshot tests
        run: npm run storybook:build && npm run test:screenshot:ci